const db = require('./database');
const Sequelize = require('sequelize');

const Apartment = db.define('apartment', {
	MLS: Sequelize.STRING,
	Status: Sequelize.STRING,
	StreetNumber: Sequelize.STRING,
	CompassPoint: Sequelize.STRING,
	StreetName: Sequelize.STRING,
	StreetSuffix: Sequelize.STRING,
	UnitNumber: Sequelize.STRING,
	SearchPrice: Sequelize.STRING,
	Rooms: Sequelize.STRING,
	BedroomsAllLevels: Sequelize.STRING,
	FullBaths: Sequelize.STRING,
	HalfBaths: Sequelize.STRING,
	Parking: Sequelize.STRING,
	GarageSpaces: Sequelize.STRING,
	ParkingSpaces: Sequelize.STRING,
	TypeAttached: Sequelize.STRING,
	SpecialCompensationInfo: Sequelize.STRING,
	ApproxYearBuilt: Sequelize.STRING,
	ApproxSqFt: Sequelize.STRING,
	Taxes: Sequelize.STRING,
	AssessmentIncludes: Sequelize.STRING,
	Assessment: Sequelize.STRING,
	MasterAssociationFee: Sequelize.STRING,
	SpecialAssessments: Sequelize.STRING,
	ZipCode: Sequelize.STRING,
	Stories: Sequelize.STRING,
	SoldPrice: Sequelize.STRING,
	RehabYN: Sequelize.STRING,
	RehabYear: Sequelize.STRING,
	RelistYN: Sequelize.STRING,
	ListPrice: Sequelize.STRING,
	PriceChangeagainstOriginalListPrice: Sequelize.STRING,
	ClosedDate: Sequelize.STRING,
	ListDate: Sequelize.STRING,
	ListDateReceived: Sequelize.STRING,
	ContractDate: Sequelize.STRING,
	EstimatedOccupancyDate: Sequelize.STRING,
	ExpirationDate: Sequelize.STRING,
	OffMarketDate: Sequelize.STRING,
	StatusDate: Sequelize.STRING,
	UpdateDate: Sequelize.STRING,
	UpdateDateTime: Sequelize.STRING,
});

module.exports = Apartment;
